# bash-tools loader - source this from ~/.bashrc
_bash_tools_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$_bash_tools_dir/cr.sh"
source "$_bash_tools_dir/ssha.sh"
source "$_bash_tools_dir/extract.sh"
source "$_bash_tools_dir/peek.sh"
source "$_bash_tools_dir/mkcd.sh"
source "$_bash_tools_dir/up.sh"
source "$_bash_tools_dir/gclean.sh"
source "$_bash_tools_dir/bak.sh"
source "$_bash_tools_dir/serve.sh"
source "$_bash_tools_dir/ports.sh"
source "$_bash_tools_dir/hist.sh"
source "$_bash_tools_dir/json.sh"
source "$_bash_tools_dir/jwt.sh"
source "$_bash_tools_dir/gdiff.sh"
source "$_bash_tools_dir/path.sh"
source "$_bash_tools_dir/envg.sh"
source "$_bash_tools_dir/calc.sh"
source "$_bash_tools_dir/epoch.sh"
source "$_bash_tools_dir/mkpr.sh"
source "$_bash_tools_dir/fff.sh"
source "$_bash_tools_dir/jlog.sh"
source "$_bash_tools_dir/dmsg.sh"
source "$_bash_tools_dir/cpu.sh"
source "$_bash_tools_dir/gpu.sh"
source "$_bash_tools_dir/fsof.sh"
source "$_bash_tools_dir/cdpath.sh"
source "$_bash_tools_dir/apts.sh"
source "$_bash_tools_dir/pss.sh"
source "$_bash_tools_dir/psk.sh"
source "$_bash_tools_dir/memback.sh"
source "$_bash_tools_dir/grepos.sh"
source "$_bash_tools_dir/hclean.sh"
source "$_bash_tools_dir/ksec.sh"
source "$_bash_tools_dir/tools.sh"

# machine-specific overrides (gitignored)
[[ -f "$_bash_tools_dir/site.sh" ]] && source "$_bash_tools_dir/site.sh"

unset _bash_tools_dir
